PATH:
  - '/home/pi/bigtooth/dev/statusLights'
lights:
  name: 'gps'
  gpio: 26

serialPort: "/dev/ttyUSB0"
gpsDatabase: "/opt/data/gps/current/gps.sqlite"
databaseSchema: "CREATE TABLE gps(n_lat integer,w_long integer,\
        date_time integer,obs_time integer,obs_date int);"
